# Generated by Django 4.1 on 2022-09-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calori', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'CUSTOMER'), (1, 'ADMIN')], default=0),
        ),
    ]
