# Generated by Django 4.1 on 2022-10-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calori', '0003_activity_item_useractivity_itemconsumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.IntegerField(choices=[(0, 'VEGETABLES'), (1, 'FRUITS'), (2, 'GRAINS, BEANS AND NUTS'), (3, 'MEAT AND POULTRY'), (4, 'FISH AND SEAFOOD'), (5, 'DAIRY FOODS')], default=0),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
