# Generated by Django 4.1 on 2022-10-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calori', '0004_remove_useractivity_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.IntegerField(choices=[(0, 'Vegetables'), (1, 'Fruits'), (2, 'Grains'), (3, 'Meat And Poultry'), (4, 'Fish And Seafood'), (5, 'Dairy Foods'), (6, 'Beans'), (7, 'Nuts')], default=0),
        ),
    ]
