# Generated by Django 4.1 on 2022-10-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calori', '0005_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='calories',
            field=models.FloatField(default=0),
        ),
    ]
