# Generated by Django 4.1.3 on 2023-04-11 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wardallot1',
            fields=[
                ('allot_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('starting_date', models.CharField(max_length=50, null=True)),
                ('ending_date', models.CharField(max_length=50, null=True)),
                ('duty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.duty')),
                ('hks_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.harithakaramasena')),
                ('ward_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ward')),
            ],
            options={
                'db_table': 'wardallot1',
            },
        ),
    ]
