# Generated by Django 4.1.3 on 2023-04-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_wardallot1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wardallot',
        ),
    ]
