# Generated by Django 4.1.3 on 2023-04-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_idgen_collection_id_housecollectiondetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='house3',
            name='house_email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
