# Generated by Django 4.1.3 on 2023-04-26 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_house3_house_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgen',
            name='function_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='function',
            fields=[
                ('function_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('function_date', models.CharField(max_length=50, null=True)),
                ('function_type', models.CharField(max_length=50, null=True)),
                ('house_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.house3')),
                ('ward_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ward')),
            ],
            options={
                'db_table': 'function',
            },
        ),
    ]
