# Generated by Django 4.1.3 on 2023-04-28 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_idgen_function_id_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgen',
            name='foodbalance_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='foodbalance',
            fields=[
                ('foodbalance_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('food_type', models.CharField(max_length=50, null=True)),
                ('food_quantity', models.CharField(max_length=50, null=True)),
                ('food_preparationtime', models.CharField(max_length=50, null=True)),
                ('food_usebefore', models.CharField(max_length=50, null=True)),
                ('food_collectionpoint', models.CharField(max_length=50, null=True)),
                ('function_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.function')),
            ],
            options={
                'db_table': 'foodbalance',
            },
        ),
    ]
