# Generated by Django 4.1.3 on 2023-05-02 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_function_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgen',
            name='foodrequest_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='requestfood',
            fields=[
                ('foodrequest_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('request_time', models.CharField(max_length=50, null=True)),
                ('request_date', models.CharField(max_length=50, null=True)),
                ('foodbalance_id_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foodbalance')),
                ('house_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.house3')),
            ],
            options={
                'db_table': 'requestfood',
            },
        ),
    ]
