# Generated by Django 4.1.3 on 2023-05-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_idgen_foodrequest_id_requestfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfood',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
