# Generated by Django 4.1.3 on 2023-05-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_requestfood_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='housecollectiondetails',
            name='collection_material',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
