# Generated by Django 4.1.3 on 2023-05-05 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_housecollectiondetails_collection_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgen',
            name='payment_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('payment_month', models.CharField(max_length=50, null=True)),
                ('payment_date', models.CharField(max_length=50, null=True)),
                ('payment_amount', models.CharField(max_length=50, null=True)),
                ('hks_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.harithakaramasena')),
                ('house_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.house3')),
                ('payment_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.duty')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
