# Generated by Django 4.1.3 on 2023-05-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_payment_material_payment_duty_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='duty_id',
        ),
    ]
