# Generated by Django 4.1.3 on 2023-05-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_payment_duty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='request_income',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
