# Generated by Django 4.1.3 on 2023-05-06 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_applications_request_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='local_id',
            field=models.ForeignKey(default='local_id1', on_delete=django.db.models.deletion.CASCADE, to='app.localbody'),
            preserve_default=False,
        ),
    ]
