# Generated by Django 4.1.3 on 2023-05-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_applications_local_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardallot1',
            name='hks_id',
        ),
    ]
