# Generated by Django 4.1.3 on 2023-05-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_wardallot1_hks_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseallot',
            name='house_number',
        ),
        migrations.AddField(
            model_name='houseallot',
            name='ending_housenumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='houseallot',
            name='starting_housenumber',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
