# Generated by Django 4.1.3 on 2023-05-19 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_houseallot_house_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseallot',
            name='ending_housenumber',
        ),
        migrations.RemoveField(
            model_name='houseallot',
            name='starting_housenumber',
        ),
        migrations.AddField(
            model_name='houseallot',
            name='house_number',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='app.house3'),
            preserve_default=False,
        ),
    ]
