# Generated by Django 4.1.3 on 2023-05-19 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_houseallot_ending_housenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseallot',
            name='ward_id',
        ),
        migrations.AddField(
            model_name='houseallot',
            name='allot_id',
            field=models.ForeignKey(default='allot_id6', on_delete=django.db.models.deletion.CASCADE, to='app.wardallot1'),
            preserve_default=False,
        ),
    ]
