# Generated by Django 4.1.3 on 2023-05-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_houseallot_ward_id_houseallot_allot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='request_aadhardcard',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='request_inomecertificate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
