# Generated by Django 4.1.3 on 2023-05-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_applications_request_aadhardcard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_finalamount',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_sack',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
